name_pfx_1L_chr <- "ready4_"
classes_to_make_tb <- dplyr::bind_rows(
  ready4class::make_pt_ready4_constructor_tbl(make_s3_lgl = TRUE,
                                              name_stub_chr = "dist",
                                              pt_ls = list(list("list")),
                                              pt_chkr_pfx_ls = list(list("is.")),
                                              pt_ns_ls = list(list("base")),
                                              vals_ls = list(list(distribution_chr = "character(0)",
                                                                  dist_param_1_dbl = "numeric(0)",
                                                                  dist_param_2_dbl = "numeric(0)",
                                                                  dist_param_3_dbl = "numeric(0)",
                                                                  dist_param_4_dbl = "numeric(0)",
                                                                  transformation_chr = "character(0)")),
                                              class_desc_chr = "ready4 S3 class for list object that summarises the parameters of each distribution"),
  ready4class::make_pt_ready4_constructor_tbl(make_s3_lgl = TRUE,
                                              name_stub_chr = "dv_import_lup",
                                              pt_ls = list(list("tibble")),
                                              pt_chkr_pfx_ls = list(list("is_")),
                                              pt_ns_ls = list(list("tibble")),
                                              vals_ls = list(list(file_type_chr = "character(0)",
                                                                  file_name_chr = "character(0)",
                                                                  data_repo_chr = "character(0)",
                                                                  data_repo_ui_chr = "character(0)",
                                                                  data_repo_db_ui_chr = "character(0)",
                                                                  data_repo_file_ext_chr = "character(0)",
                                                                  data_repo_save_type_chr = "character(0)")),
                                              class_desc_chr = "ready4 S3 class for tibble object lookup table of files to be imported from a dataverse."),
  ready4class::make_pt_ready4_constructor_tbl(make_s3_lgl = TRUE,
                                              name_stub_chr = "all_import_lup",
                                              pt_ls = list(list("tibble")),
                                              pt_chkr_pfx_ls = list(list("is_")),
                                              pt_ns_ls = list(list("tibble")),
                                              vals_ls = list(list(local_file_src_chr = "character(0)",
                                                                  path_to_make_script_chr = "character(0)",
                                                                  download_url_chr = "character(0)",
                                                                  inc_file_main_chr = "character(0)",
                                                                  inc_fls_to_rename_ls = "list()",
                                                                  new_nms_for_inc_fls_ls = "list()")),
                                              class_desc_chr = "ready4 S3 class for tibble object lookup table of sources of raw (un-processed) data to import.",
                                              parent_class_chr = "ready4_dv_import_lup"),
  ready4class::make_pt_ready4_constructor_tbl(make_s3_lgl = TRUE,
                                              name_stub_chr = "par_struc_mape",
                                              pt_ls = list(list("tibble")),
                                              pt_chkr_pfx_ls = list(list("is_")),
                                              pt_ns_ls = list(list("tibble")),
                                              vals_ls = list(list(param_name_chr = "character(0)",
                                                                  sex_age_band_chr = "character(0)",
                                                                  mape_05_yr_mde_dbl = "numeric(0)",
                                                                  mape_10_yr_mde_dbl = "numeric(0)",
                                                                  mape_15_yr_mde_dbl = "numeric(0)",
                                                                  mape_05_yr_min_dbl = "numeric(0)",
                                                                  mape_10_yr_min_dbl = "numeric(0)",
                                                                  mape_15_yr_min_dbl = "numeric(0)",
                                                                  mape_05_yr_max_dbl = "numeric(0)",
                                                                  mape_10_yr_max_dbl = "numeric(0)",
                                                                  mape_15_yr_max_dbl = "numeric(0)",
                                                                  mape_05_yr_shp_dbl = "numeric(0)",
                                                                  mape_10_yr_shp_dbl = "numeric(0)",
                                                                  mape_15_yr_shp_dbl = "numeric(0)")),
                                              class_desc_chr = "ready4 S3 class for tibble object that stores simulation structural parameters relating to Mean Absolute Prediction Errors."),
  ready4class::make_pt_ready4_constructor_tbl(make_s3_lgl = T,
                                              name_stub_chr = "dictionary",
                                              pt_ls = list(list("tibble")),
                                              pt_chkr_pfx_ls = list(list("is_")),
                                              pt_ns_ls = list(list("tibble")),
                                              vals_ls = list(list(var_nm_chr = "character(0)",
                                                                  var_ctg_chr = "character(0)",
                                                                  var_desc_chr = "character(0)",
                                                                  var_type_chr = "character(0)")),
                                              class_desc_chr= "ready4 s3 class defining a data dictionary tibble."),
  ready4class::make_pt_ready4_constructor_tbl(make_s3_lgl = FALSE,
                                              name_stub_chr = "local",
                                              slots_ls = c("merge_with_chr_vec","raw_data_dir_chr","pckg_chr","overwrite_lgl", "save_lgl") %>% list(), # Cut: "lup_tbs_r4",
                                              pt_ls = c("character","character","character","logical", "logical") %>% list(), # Cut: "ready4_lookup",
                                              class_desc_chr= "ready4 S4 class defining data to be saved in local directory.",
                                              parent_class_chr = NA_character_), # Cut: ,include_classes = list("ready4_lookup")
  ready4class::make_pt_ready4_constructor_tbl(make_s3_lgl = FALSE,
                                              name_stub_chr = "local_raw",
                                              slots_ls = c("save_type") %>% list(),
                                              pt_ls = c("character") %>% list(),
                                              vals_ls = list(save_type ="raw"),
                                              allowed_vals_ls = list(save_type = "raw"),
                                              class_desc_chr= "ready4 S4 class defining data to be saved in local directory in a raw (unprocessed) format.",
                                              parent_class_chr = "ready4_local",
                                              inc_clss_ls = list("ready4_local")),
  ready4class::make_pt_ready4_constructor_tbl(make_s3_lgl = FALSE,
                                              name_stub_chr = "local_proc",
                                              slots_ls = c("save_type","proc_data_dir_chr","import_chr_vec","path_to_starter_sf_chr","import_this_ls") %>% list(),
                                              pt_ls = c("character","character","character","character","list") %>% list(),
                                              vals_ls = list(save_type = "proc"),
                                              allowed_vals_ls = list(save_type = "proc"),
                                              class_desc_chr= "ready4 S4 class defining data to be saved in local directory in a processed (R) format.",
                                              parent_class_chr = "ready4_local",
                                              inc_clss_ls = list("ready4_local")),
  ready4class::make_pt_ready4_constructor_tbl(make_s3_lgl = FALSE,
                                              name_stub_chr = "script_data",
                                              slots_ls = c("crs_nbr_dbl") %>% list(), # Change
                                              pt_ls = c("numeric") %>% list(),
                                              class_desc_chr= "ready4 S4 class containing data to be passed to a function that constructs a spatial object from a lookup table.",
                                              parent_class_chr = "ready4_local_proc",
                                              inc_clss_ls = list("ready4_local_proc"))
) %>%
  ready4class::ready4_constructor_tbl()
